### ISSUE TITLE
Make Toolbar's Action Done option of Gallery Pickup Customizable.

### ISSUE THREAD

**Issue by brittle123** [wuapnjie/PoiPhoto#5]
As in the image attached the Done option shows in black color and the other thing is it is in chinese. Please alter your PhotoPicker ASAP!.
Regards & Thanks.

![Screenshot_20190626-162634 1](https://user-images.githubusercontent.com/66940181/89978210-67988a80-dc86-11ea-8fa7-642ae6be9f93.png)

**Comment by thefaisalurrehman** [comment]
> As in the image attached the Done option shows in black color and the other thing is it is in chinese. Please alter your PhotoPicker ASAP!.
> Regards & Thanks.
> 
> ![Screenshot_20190626-162634 1](https://user-images.githubusercontent.com/66940181/89978210-67988a80-dc86-11ea-8fa7-642ae6be9f93.png)

Can You Find Any Solution for Done Button(完成)?

**Comment by brittle123** [comment]
Yes I did resolve it by using this https://github.com/OpenSooq/Gligar for selecting pictures.
